[package]
name = "ffengine"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25"
winit = { version = "0.29"}
ash = { version = "0.38", features = ["linked", "debug", "std"] }
ash-window = { version = "0.13.0" }
json = "0.12.4"